apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: lrps.kapi.cf.org
spec:
  group: kapi.cf.org
  version: v1alpha1
  scope: Namespaced
  names:
    plural: lrps
    singular: lrp
    kind: LRP
    shortNames:
    - lrp
