apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stagings.kapi.cf.org
spec:
  group: kapi.cf.org
  version: v1alpha1
  scope: Namespaced
  names:
    plural: stagings
    singular: staging
    kind: Staging
    shortNames:
    - stg
  subresources:
    status: {}
