---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapi-eirini-admin
  namespace: kapini
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kapi-eirini-clust-admin-binding
subjects:
  - kind: ServiceAccount
    name: kapi-eirini-admin
    namespace: kapini
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
